
echo "----------------------------"
echo "Loaded bashrc"
echo ""
echo "To edit run: bashedit"
echo "To refresh run: bashrefresh"
echo "All aliases: alias"
echo "----------------------------"

alias S4="cd ~/S4/sigdca-s41-webapp"
alias S42F="cd ~/S42/S42-front"
alias S42B="cd ~/S42/S42-back"
alias cleanstallnotest="mvn clean install -Dmaven.test.skip=true"
alias S42G="cd ~/s42-geoserver-workspace"
alias S43F="cd ~/S43/s43-front/"
alias S43B="cd ~/S43/s43-back/"
alias refet="cd ~/sref-et/"
alias Lrefet="cd ~/sref-et/ && mvn clean install generate-sources -Dmaven.test.skip=true && java -jar -Dspring.profiles.active=dev sref-et-back-spring-webapp/target/referentiel-et-back-springboot-0.2.0-SNAPSHOT.war"
alias glog="git log --format=format:\"%C(auto)%h %C(green)%aN%Creset %s\""
alias co="git checkout"
alias ng-sidca="cd ~/ng-sidca/"
alias common="cd ~/sigdca-common/"
alias suit="cd /D/Dvpt/Projets/Dev2022/suit/suit"
alias servesuit="node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng serve"
alias ignoreuntracked="git ls-files --others --exclude-standard >> .gitignore"
alias rebasedevelop="git fetch origin && git rebase origin develop"
alias 0.4="cd /D/Dvpt/Projets/Dev2022/suit.0-4/suit"
alias setup="cd D:/Dvpt/Tools/Scripts && sh setup_enviro.sh"
alias shalom="cd ~/perso/shalomalerhem"
alias pushbash="cd ~/perso/myBashrc && git add . && git commit -m \"update\" && git push origin master"
